// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFtAnbXHFScKv_T6V9IYrG5_kEyhLHeXc',
    appId: '1:768356607276:web:ad7c5076054d7908c2b889',
    messagingSenderId: '768356607276',
    projectId: 'myfirstapp-16313',
    authDomain: 'myfirstapp-16313.firebaseapp.com',
    storageBucket: 'myfirstapp-16313.appspot.com',
    measurementId: 'G-VVTWDVLFTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJvs7saSAM7C9_H2uPWTViKDcBdNAh5kM',
    appId: '1:768356607276:android:c6943159446ef3fec2b889',
    messagingSenderId: '768356607276',
    projectId: 'myfirstapp-16313',
    storageBucket: 'myfirstapp-16313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufqFVnMx0XP_DpPt0F24cTjKnXIsndn4',
    appId: '1:768356607276:ios:1ffa1f0b274f1dabc2b889',
    messagingSenderId: '768356607276',
    projectId: 'myfirstapp-16313',
    storageBucket: 'myfirstapp-16313.appspot.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufqFVnMx0XP_DpPt0F24cTjKnXIsndn4',
    appId: '1:768356607276:ios:1ffa1f0b274f1dabc2b889',
    messagingSenderId: '768356607276',
    projectId: 'myfirstapp-16313',
    storageBucket: 'myfirstapp-16313.appspot.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFtAnbXHFScKv_T6V9IYrG5_kEyhLHeXc',
    appId: '1:768356607276:web:ffbfe0fb957c2deec2b889',
    messagingSenderId: '768356607276',
    projectId: 'myfirstapp-16313',
    authDomain: 'myfirstapp-16313.firebaseapp.com',
    storageBucket: 'myfirstapp-16313.appspot.com',
    measurementId: 'G-4S7MS3PL2J',
  );

}